services:
  fcp-defra-id-stub:
    image: defradigital/fcp-defra-id-stub:0.47.0
    networks:
      - grants-ui-net
    environment:
      WELL_KNOWN_HOST_OVERRIDE: '${WELL_KNOWN_HOST_OVERRIDE:-http://localhost:3007}'
      WELL_KNOWN_API_HOST_OVERRIDE: '${WELL_KNOWN_API_HOST_OVERRIDE:-http://fcp-defra-id-stub:3007}'
      PORT: 3007
      ALLOW_LOGIN_QUERY_PARAMS: ${ALLOW_LOGIN_QUERY_PARAMS:-true}
      AUTH_MODE: ${AUTH_MODE:-basic}
      AUTH_OVERRIDE: ${AUTH_OVERRIDE:-}
      AUTH_OVERRIDE_FILE: ${AUTH_OVERRIDE_FILE:-users.json}
    volumes:
      - ./fcp-defra-id-stub/users.json:/data/users.json
    ports:
      - '3007:3007'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3007/health']
      interval: 30s
      start_interval: 1s
      timeout: 3s
      retries: 3
      start_period: 10s

  grants-ui-dal-stub:
    image: defradigital/grants-ui-dal-stub:latest
    pull_policy: always
    ports:
      - '3008:3008'
    environment:
      PORT: 3008
      NODE_ENV: ${NODE_ENV:-development}
    networks:
      - grants-ui-net
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3008/health']
      interval: 30s
      start_interval: 1s
      timeout: 3s
      retries: 3
      start_period: 10s

  mockserver:
    image: mockserver/mockserver:5.15.0
    networks:
      - grants-ui-net
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/expectations.json
    ports:
      - '1080:1080'
    volumes:
      - ./mockserver/expectations.json:/config/expectations.json
    command:
      - -serverPort 1080 -logLevel INFO

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      start_interval: 1s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - grants-ui-net

  mongodb:
    image: mongo:7.0
    networks:
      - grants-ui-net
    ports:
      - '${MONGO_PORT:-27017}:27017'
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', "db.adminCommand('ping').ok"]
      interval: 30s
      start_interval: 1s
      timeout: 3s
      retries: 5
      start_period: 10s
    command: ['mongod', '--replSet', 'mongoRepl', '--bind_ip', 'localhost,mongodb']
    restart: always

  mongo-ready:
    image: mongo:7.0
    networks: [grants-ui-net]
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      PRIMARY: 'mongodb:27017'
      REPLSET: 'mongoRepl'
    volumes:
      - ./scripts/wait-for-replicaset.sh:/wait-for-replicaset.sh:ro
    entrypoint: ['/bin/bash', '/wait-for-replicaset.sh']
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mongosh "mongodb://mongodb:27017/?directConnection=true" --quiet --eval "db.hello().isWritablePrimary" | grep -q true'
        ]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 5s

  floci:
    image: floci/floci:latest-compat
    ports:
      - '4566:4566'
    env_file:
      - 'compose/aws.env'
    environment:
      FLOCI_DEFAULT_REGION: eu-west-2
      FLOCI_REQUIRED_S3_BUCKETS: configs-bucket
      FLOCI_REQUIRED_SQS_QUEUES: fcp_audit,gfr__sqs___config_input,grants_ui_backend__sqs__config_updates
      FLOCI_REQUIRED_SNS_TOPICS: fcp_audit_events,gfr__sns___config_update  
    volumes:
      - ./compose/floci/common/10-setup-resources.sh:/etc/floci/init/start.d/10-setup-resources.sh:ro
      - ./compose/floci/check-floci-resources.sh:/usr/local/bin/check-floci-resources.sh:ro
      - ./compose/forms:/etc/forms:ro
    # healthcheck:
    #   test: ['CMD-SHELL', '/usr/local/bin/check-floci-resources.sh']
    #   interval: 3s
    #   start_period: 5s
    #   retries: 20
    networks:
      - grants-ui-net

volumes:
  redis-data:
  mongodb-data:
  mongodb-config:

networks:
  grants-ui-net:
    name: grants-ui-net
    driver: bridge