### Create Example Grant With Auth

# @name createExampleGrantWithAuth

POST {{base}}/grants HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{serviceToken}}
x-api-key: {{x-api-key}}

{
  "code": "example-grant-with-auth-v3",
  "metadata": {
    "description": "Example grant with auth",
    "startDate": "2025-11-20T11:44:14.999Z"
  },
  "actions": [],
  "phases": [
    {
      "code": "PRE_AWARD",
      "name": "Pre-award",
      "description": "Pre-award phase",
      "questions": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "additionalProperties": false,
        "required": [
          "yesNoField",
          "autocompleteField",
          "radiosField",
          "checkboxesField",
          "numberField",
          "datePartsField__day",
          "datePartsField__month",
          "datePartsField__year",
          "monthYearField__month",
          "monthYearField__year",
          "selectField",
          "multilineTextField",
          "applicantName",
          "applicantEmail",
          "applicantMobile",
          "applicantBusinessAddress__addressLine1",
          "applicantBusinessAddress__town",
          "applicantBusinessAddress__postcode"
        ],
        "properties": {
          "yesNoField": { "type": "boolean" },
          "autocompleteField": { "type": "string" },
          "radiosField": { "type": "string" },
          "checkboxesField": { "type": "array", "items": { "type": "string" } },
          "numberField": { "type": "number" },
          "datePartsField__day": { "type": "number" },
          "datePartsField__month": { "type": "number" },
          "datePartsField__year": { "type": "number" },
          "monthYearField__month": { "type": "number" },
          "monthYearField__year": { "type": "number" },
          "selectField": { "type": "string" },
          "multilineTextField": { "type": "string" },
          "applicantName": { "type": "string" },
          "applicantEmail": { "type": "string", "format": "email" },
          "applicantMobile": { "type": "string" },
          "applicantBusinessAddress__addressLine1": { "type": "string" },
          "applicantBusinessAddress__addressLine2": {
            "type": ["string", "null"]
          },
          "applicantBusinessAddress__town": { "type": "string" },
          "applicantBusinessAddress__county": { "type": ["string", "null"] },
          "applicantBusinessAddress__postcode": { "type": "string" }
        }
      },
      "stages": [
        {
          "code": "REVIEW_APPLICATION",
          "name": "Review Application",
          "description": "Review the application for eligibility",
          "statuses": [
            {
              "code": "APPLICATION_RECEIVED"
            },
            {
              "code": "IN_REVIEW",
              "validFrom": [
                "APPLICATION_RECEIVED"
              ]
            },
            {
              "code": "AGREEMENT_GENERATING",
              "validFrom": [
                "IN_REVIEW"
              ],
              "processes": [
                "GENERATE_OFFER"
              ]
            },
            {
              "code": "APPLICATION_WITHDRAWN",
              "validFrom": [
                "IN_REVIEW"
              ]
            }
          ]
        },
        {
          "code": "REVIEW_OFFER",
          "name": "Review Offer",
          "description": "Review the offer made to the applicant",
          "statuses": [
            {
              "code": "OFFER_SENT",
              "validFrom": [
                "PRE_AWARD:REVIEW_APPLICATION:AGREEMENT_GENERATING"
              ],
              "processes": [
                "STORE_AGREEMENT_CASE"
              ]
            }
          ]
        },
        {
          "code": "CUSTOMER_AGREEMENT_REVIEW",
          "name": "Customer Agreement Review",
          "description": "Customer reviews the agreement offer",
          "statuses": [
            {
              "code": "OFFER_SENT",
              "validFrom": [
                "PRE_AWARD:REVIEW_OFFER:OFFER_SENT"
              ]
            }
          ]
        }
      ]
    },
    {
      "code": "POST_AGREEMENT_MONITORING",
      "name": "Post Agreement Monitoring",
      "stages": [
        {
          "code": "MONITORING",
          "name": "Monitoring",
          "statuses": [
            {
              "code": "OFFER_ACCEPTED",
              "validFrom": [
                "PRE_AWARD:CUSTOMER_AGREEMENT_REVIEW:AGREEMENT_OFFERED"
              ],
              "processes": [
                "UPDATE_AGREEMENT_CASE"
              ]
            },
            {
              "code": "COMPLETE_AGREEMENT",
              "validFrom": [
                "OFFER_ACCEPTED"
              ]
            }
          ]
        }
      ]
    }
  ],
  "externalStatusMap": {
    "phases": [
      {
        "code": "PRE_AWARD",
        "stages": [
          {
            "code": "REVIEW_APPLICATION",
            "statuses": [
              {
                "code": "IN_REVIEW",
                "source": "CW",
                "mappedTo": "PRE_AWARD:REVIEW_APPLICATION:IN_REVIEW"
              },
              {
                "code": "AGREEMENT_GENERATING",
                "source": "CW",
                "mappedTo": "PRE_AWARD:REVIEW_APPLICATION:AGREEMENT_GENERATING"
              },
              {
                "code": "APPLICATION_REJECTED",
                "source": "CW",
                "mappedTo": "PRE_AWARD:REVIEW_APPLICATION:APPLICATION_REJECTED"
              },
              {
                "code": "offered",
                "source": "AS",
                "mappedTo": "PRE_AWARD:REVIEW_OFFER:OFFER_SENT"
              }
            ]
          },
          {
            "code": "REVIEW_OFFER",
            "statuses": [
              {
                "code": "rejected",
                "source": "AS",
                "mappedTo": "PRE_AWARD:REVIEW_OFFER:OFFER_REJECTED"
              }
            ]
          },
          {
            "code": "CUSTOMER_AGREEMENT_REVIEW",
            "statuses": [
              {
                "code": "AGREEMENT_OFFERED",
                "source": "CW",
                "mappedTo": "PRE_AWARD:CUSTOMER_AGREEMENT_REVIEW:AGREEMENT_OFFERED"
              },
              {
                "code": "accepted",
                "source": "AS",
                "mappedTo": "POST_AGREEMENT_MONITORING:MONITORING:OFFER_ACCEPTED"
              },
              {
                "code": "withdrawn",
                "source": "AS",
                "mappedTo": "PRE_AWARD:CUSTOMER_AGREEMENT_REVIEW:OFFER_WITHDRAWN"
              }
            ]
          }
        ]
      },
      {
        "code": "POST_AGREEMENT_MONITORING",
        "stages": [
          {
            "code": "MONITORING",
            "statuses": [
              {
                "code": "OFFER_ACCEPTED",
                "source": "CW",
                "mappedTo": "POST_AGREEMENT_MONITORING:MONITORING:OFFER_ACCEPTED"
              },
              {
                "code": "COMPLETE_AGREEMENT",
                "source": "CW",
                "mappedTo": "POST_AGREEMENT_MONITORING:MONITORING:COMPLETE_AGREEMENT"
              }
            ]
          }
        ]
      }
    ]
  }
}


### Submit application for Example Grant With Auth

# @name submitExampleGrantWithAuthApplication

POST {{base}}/grants/example-grant-with-auth-v3/applications HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{serviceToken}}

{
  "answers": {
    "referenceNumber": "EGWA-123-ABC",
    "yesNoField": true,
    "autocompleteField": "WAL",
    "radiosField": "radiosFieldOption-A2",
    "checkboxesField": ["checkboxesFieldOption-A2"],
    "numberField": 100000,
    "datePartsField__day": 1,
    "datePartsField__month": 12,
    "datePartsField__year": 2025,
    "monthYearField__month": 12,
    "monthYearField__year": 2026,
    "selectField": "selectFieldOption-A4",
    "multilineTextField": "This is a test",
    "applicantName": "John Smith",
    "applicantEmail": "john.smith@example.com",
    "applicantMobile": "07111 111111",
    "applicantBusinessAddress__addressLine1": "111 Test Street",
    "applicantBusinessAddress__town": "Testville",
    "applicantBusinessAddress__postcode": "TE5 7PO"
  },
  "metadata": {
    "clientRef": "{{$uuid}}",
    "crn": "1234567890",
    "defraId": "1234567890",
    "frn": "1234567890",
    "sbi": "1234567890",
    "submittedAt": "{{$isoTimestamp}}"
  }
}

### Create Adding Value

# @name createAddingValue

POST {{base}}/grants HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{serviceToken}}
x-api-key: {{x-api-key}}

{
  "code": "adding-value",
  "metadata": {
    "description": "Adding Value",
    "startDate": "2025-11-21T11:00:00.000Z"
  },
  "actions": [],
  "phases": [
    {
      "code": "PRE_AWARD",
      "name": "Pre-award",
      "description": "Pre-award phase",
      "questions": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "additionalProperties": false,
        "required": [
          "referenceNumber",
          "businessNature",
          "businessLegalStatus",
          "isInEngland",
          "planningPermissionStatus",
          "projectStartStatus",
          "isLandBusinessOwned",
          "isBuildingSmallerAbattoir",
          "estimatedCost",
          "canPayRemainingCosts",
          "hasMechanisationUsage",
          "grantApplicantType",
          "applicantFirstName",
          "applicantLastName",
          "applicantEmail",
          "applicantEmailConfirmation",
          "applicantMobile",
          "applicantLandline",
          "applicantBusinessAddress__addressLine1",
          "applicantBusinessAddress__town",
          "applicantBusinessAddress__postcode",
          "applicantProjectPostcode"
        ],
        "properties": {
          "referenceNumber": { "type": "string" },
          "businessNature": { "type": "string" },
          "businessLegalStatus": { "type": "string" },
          "isInEngland": { "type": "boolean" },
          "planningPermissionStatus": { "type": "string" },
          "projectStartStatus": { "type": "string" },
          "isLandBusinessOwned": { "type": "boolean" },
          "hasFiveYearTenancyAgreement": { "type": "boolean" },
          "isBuildingSmallerAbattoir": { "type": "boolean" },
          "isBuildingFruitStorage": { "type": "boolean" },
          "isProvidingServicesToOtherFarmers": { "type": "boolean" },
          "projectItemsNeeded": { "type": "boolean" },
          "eligibleItems": {
            "type": "array",
            "items": { "type": "string" }
          },
          "needsStorageFacilities": { "type": "string" },
          "estimatedCost": { "type": "number" },
          "canPayRemainingCosts": { "type": "boolean" },
          "processedProduceType": { "type": "string" },
          "valueAdditionMethod": { "type": "string" },
          "impactType": {
            "type": "array",
            "items": { "type": "string" }
          },
          "hasMechanisationUsage": { "type": "boolean" },
          "manualLabourEquivalence": { "type": "string" },
          "hasFutureCustomers": { "type": "boolean" },
          "futureCustomerTypes": {
            "type": "array",
            "items": { "type": "string" }
          },
          "collaboration": { "type": "boolean" },
          "hasEnvironmentImpact": { "type": "boolean" },
          "environmentalImpactTypes": {
            "type": "array",
            "items": { "type": "string" }
          },
          "grantApplicantType": { "type": "string" },
          "agentFirstName": { "type": "string" },
          "agentLastName": { "type": "string" },
          "agentBusinessName": { "type": "string" },
          "agentEmail": { "type": "string", "format": "email" },
          "agentEmailConfirmation": { "type": "string", "format": "email" },
          "agentMobile": { "type": "string" },
          "agentLandline": { "type": "string" },
          "agentBusinessAddress__addressLine1": { "type": "string" },
          "agentBusinessAddress__addressLine2": {
            "type": ["string", "null"]
          },
          "agentBusinessAddress__town": { "type": "string" },
          "agentBusinessAddress__county": { "type": ["string", "null"] },
          "agentBusinessAddress__postcode": { "type": "string" },
          "applicantFirstName": { "type": "string" },
          "applicantLastName": { "type": "string" },
          "applicantEmail": { "type": "string", "format": "email" },
          "applicantEmailConfirmation": {
            "type": "string",
            "format": "email"
          },
          "applicantMobile": { "type": "string" },
          "applicantLandline": { "type": "string" },
          "applicantBusinessAddress__addressLine1": { "type": "string" },
          "applicantBusinessAddress__addressLine2": {
            "type": ["string", "null"]
          },
          "applicantBusinessAddress__town": { "type": "string" },
          "applicantBusinessAddress__county": { "type": ["string", "null"] },
          "applicantBusinessAddress__postcode": { "type": "string" },
          "applicantProjectPostcode": { "type": "string" }
        }
      },
      "stages": [
        {
          "code": "REVIEW_APPLICATION",
          "name": "Review Application",
          "description": "Review the application for eligibility",
          "statuses": [
            {
              "code": "APPLICATION_RECEIVED"
            },
            {
              "code": "IN_REVIEW",
              "validFrom": [
                "APPLICATION_RECEIVED"
              ]
            },
            {
              "code": "AGREEMENT_GENERATING",
              "validFrom": [
                "IN_REVIEW"
              ],
              "processes": [
                "GENERATE_OFFER"
              ]
            },
            {
              "code": "APPLICATION_WITHDRAWN",
              "validFrom": [
                "IN_REVIEW"
              ]
            }
          ]
        },
        {
          "code": "REVIEW_OFFER",
          "name": "Review Offer",
          "description": "Review the offer made to the applicant",
          "statuses": [
            {
              "code": "OFFER_SENT",
              "validFrom": [
                "PRE_AWARD:REVIEW_APPLICATION:AGREEMENT_GENERATING"
              ],
              "processes": [
                "STORE_AGREEMENT_CASE"
              ]
            }
          ]
        },
        {
          "code": "CUSTOMER_AGREEMENT_REVIEW",
          "name": "Customer Agreement Review",
          "description": "Customer reviews the agreement offer",
          "statuses": [
            {
              "code": "OFFER_SENT",
              "validFrom": [
                "PRE_AWARD:REVIEW_OFFER:OFFER_SENT"
              ]
            }
          ]
        }
      ]
    },
    {
      "code": "POST_AGREEMENT_MONITORING",
      "name": "Post Agreement Monitoring",
      "stages": [
        {
          "code": "MONITORING",
          "name": "Monitoring",
          "statuses": [
            {
              "code": "OFFER_ACCEPTED",
              "validFrom": [
                "PRE_AWARD:CUSTOMER_AGREEMENT_REVIEW:AGREEMENT_OFFERED"
              ],
              "processes": [
                "UPDATE_AGREEMENT_CASE"
              ]
            },
            {
              "code": "COMPLETE_AGREEMENT",
              "validFrom": [
                "OFFER_ACCEPTED"
              ]
            }
          ]
        }
      ]
    }
  ],
  "externalStatusMap": {
    "phases": [
      {
        "code": "PRE_AWARD",
        "stages": [
          {
            "code": "REVIEW_APPLICATION",
            "statuses": [
              {
                "code": "IN_REVIEW",
                "source": "CW",
                "mappedTo": "PRE_AWARD:REVIEW_APPLICATION:IN_REVIEW"
              },
              {
                "code": "AGREEMENT_GENERATING",
                "source": "CW",
                "mappedTo": "PRE_AWARD:REVIEW_APPLICATION:AGREEMENT_GENERATING"
              },
              {
                "code": "APPLICATION_REJECTED",
                "source": "CW",
                "mappedTo": "PRE_AWARD:REVIEW_APPLICATION:APPLICATION_REJECTED"
              },
              {
                "code": "offered",
                "source": "AS",
                "mappedTo": "PRE_AWARD:REVIEW_OFFER:OFFER_SENT"
              }
            ]
          },
          {
            "code": "REVIEW_OFFER",
            "statuses": [
              {
                "code": "rejected",
                "source": "AS",
                "mappedTo": "PRE_AWARD:REVIEW_OFFER:OFFER_REJECTED"
              }
            ]
          },
          {
            "code": "CUSTOMER_AGREEMENT_REVIEW",
            "statuses": [
              {
                "code": "AGREEMENT_OFFERED",
                "source": "CW",
                "mappedTo": "PRE_AWARD:CUSTOMER_AGREEMENT_REVIEW:AGREEMENT_OFFERED"
              },
              {
                "code": "accepted",
                "source": "AS",
                "mappedTo": "POST_AGREEMENT_MONITORING:MONITORING:OFFER_ACCEPTED"
              },
              {
                "code": "withdrawn",
                "source": "AS",
                "mappedTo": "PRE_AWARD:CUSTOMER_AGREEMENT_REVIEW:OFFER_WITHDRAWN"
              }
            ]
          }
        ]
      },
      {
        "code": "POST_AGREEMENT_MONITORING",
        "stages": [
          {
            "code": "MONITORING",
            "statuses": [
              {
                "code": "OFFER_ACCEPTED",
                "source": "CW",
                "mappedTo": "POST_AGREEMENT_MONITORING:MONITORING:OFFER_ACCEPTED"
              },
              {
                "code": "COMPLETE_AGREEMENT",
                "source": "CW",
                "mappedTo": "POST_AGREEMENT_MONITORING:MONITORING:COMPLETE_AGREEMENT"
              }
            ]
          }
        ]
      }
    ]
  }
}


### Submit application for Adding Value

# @name submitAddingValueApplication

POST {{base}}/grants/adding-value/applications HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{serviceToken}}

{
  "answers": {
    "referenceNumber": "AV-123-XYZ",
    "businessNature": "A grower or producer of agricultural or horticultural produce",
    "businessLegalStatus": "Sole trader",
    "isInEngland": true,
    "planningPermissionStatus": "Not needed",
    "projectStartStatus": "Yes, preparatory work",
    "isLandBusinessOwned": true,
    "hasFiveYearTenancyAgreement": true,
    "isBuildingSmallerAbattoir": true,
    "isBuildingFruitStorage": true,
    "isProvidingServicesToOtherFarmers": true,
    "projectItemsNeeded": true,
    "eligibleItems": [
      "Constructing or improving buildings for processing"
    ],
    "needsStorageFacilities": "Yes, we will need storage facilities",
    "estimatedCost": 123456,
    "canPayRemainingCosts": true,
    "processedProduceType": "Arable produce",
    "valueAdditionMethod": "Introducing a new product to your farm",
    "impactType": [
      "Increasing range of added-value products"
    ],
    "hasMechanisationUsage": true,
    "manualLabourEquivalence": "Up to 5% of workforce",
    "hasFutureCustomers": false,
    "grantApplicantType": "Applicant",
    "applicantFirstName": "John",
    "applicantLastName": "Smith",
    "applicantEmail": "john.smith@defra.gov.uk",
    "applicantEmailConfirmation": "john.smith@defra.gov.uk",
    "applicantMobile": "43432423",
    "applicantLandline": "4354654654",
    "applicantBusinessAddress__addressLine1": "Address Line One",
    "applicantBusinessAddress__addressLine2": null,
    "applicantBusinessAddress__town": "Town Or City",
    "applicantBusinessAddress__county": null,
    "applicantBusinessAddress__postcode": "CR3 5NF",
    "applicantProjectPostcode": "CR41NJ"
  },
  "metadata": {
    "clientRef": "{{$uuid}}",
    "crn": "1234567890",
    "defraId": "1234567890",
    "frn": "1234567890",
    "sbi": "1234567890",
    "submittedAt": "{{$isoTimestamp}}"
  }
}

### Get health

# @name getHealth

GET {{base}}/health HTTP/1.1
x-api-key: {{x-api-key}}
