tasklist:
  id: example
  title: Apply for example grant
  closingDate: 17 June 2025
  helpText: Contact the team if you need help, want to report a problem or want to make a change to your Grant Funding Agreement.
  
  conditions:
    otherFarmersYesOrFruitStorage:
      type: conditional
      rules:
        - if:
            and:
              - field: "facilities.isBuildingSmallerAbattoir"
                notEquals: true
              - field: "facilities.isBuildingFruitStorage"
                notEquals: true
          then: "hidden"
        - if:
            or:
              - field: "facilities.isProvidingServicesToOtherFarmers"
                equals: true
              - field: "facilities.isProvidingFruitStorage"
                equals: true
          then: "not_yet_started"
      default: "cannot_start_yet"
    
    agentDetails:
      type: conditional
      rules:
        - if:
            field: "who-is-applying.grantApplicantType"
            exists: false
          then: "hidden"
        - if:
            field: "who-is-applying.grantApplicantType"
            equals: "applying-A2"
          then: "not_yet_started"
      default: "hidden"
    
    applicantDetails:
      type: conditional
      rules:
        - if:
            field: "who-is-applying.grantApplicantType"
            exists: false
          then: "hidden"
        - if:
            field: "who-is-applying.grantApplicantType"
            equals: "applying-A1"
          then: "not_yet_started"
      default: "hidden"
  
  sections:
    - id: check-before-start
      title: 1. Check before you start
      subsections:
        - id: business-status
          title: Business status
          href: business-status
        - id: project-preparation
          title: Project preparation
          href: project-preparation

    - id: facilities
      title: 2. Facilities
      subsections:
        - id: facilities
          title: Facilities
          href: facilities

    - id: costs
      title: 3. Costs
      subsections:
        - id: costs
          title: Costs
          href: costs

    - id: impact
      title: 4. Impact
      subsections:
        - id: produce-processed
          title: Produce
          href: produce-processed
          condition: otherFarmersYesOrFruitStorage
        - id: project-impact
          title: Project
          href: project-impact
          condition: otherFarmersYesOrFruitStorage
        - id: manual-labour-amount
          title: Mechanisation
          href: manual-labour-amount
        - id: future-customers
          title: Future customers
          href: future-customers
        - id: collaboration
          title: Collaboration
          href: collaboration
        - id: environmental-impact
          title: Environment
          href: environmental-impact

    - id: finalisation
      title: 5. Finalisation
      subsections:
        - id: score-results
          title: Score results
          href: score-results
        - id: business-details
          title: Business Details
          href: business-details
        - id: who-is-applying
          title: Who is applying?
          href: who-is-applying
        - id: agent-details
          title: Agent
          href: agent-details
          condition: agentDetails
        - id: applicant-details
          title: Applicant
          href: applicant-details
          condition: applicantDetails
        - id: check-details
          title: Check your details
          href: check-details
        - id: declaration
          title: Confirm and send
          href: declaration

  statusRules:
    score-results:
      type: allComplete
      dependsOn:
        - business-status
        - project-preparation
        - facilities
        - costs
        - produce-processed
        - project-impact
        - manual-labour-amount
        - future-customers
        - collaboration
        - environmental-impact
    
    check-details:
      type: allComplete
      dependsOn:
        - business-status
        - project-preparation
        - facilities
        - costs
        - produce-processed
        - project-impact
        - manual-labour-amount
        - future-customers
        - collaboration
        - environmental-impact
        # - score-results # Uncomment when scoring page works
        - business-details
        - who-is-applying
        - agent-details
        - applicant-details
    
    declaration:
      type: allComplete
      dependsOn:
        - check-details