export const ApplicationStatus = {
  SUBMITTED: 'SUBMITTED',
  REOPENED: 'REOPENED',
  CLEARED: 'CLEARED',
  PURGED: 'PURGED',
  CLAIM_STARTED: 'CLAIM_STARTED',
  CLAIM_SUBMITTED: 'CLAIM_SUBMITTED'
}
