engine: V2
name: Environment
pages:
  - title: How will this project improve the environment?
    path: /environmental-impact
    section: environmentSection
  - title: "Check your answers: Environment"
    path: /summary
    controller: SectionEndController
lists: []
conditions: []
sections:
  - title: Environment
    name: environmentSection
    hideTitle: false
startPage: /environmental-impact
