engine: V2
name: Environment
metadata:
  id: d5e8404c-73fb-4721-b329-4ab604840e53
  tasklistId: example
  submission:
    grantCode: environmental-impact
  grantRedirectRules:
    preSubmission:
      - toPath: /check-selected-land-actions
    postSubmission:
      # Submitted -> confirmation
      - fromGrantsStatus: SUBMITTED
        gasStatus: RECEIVED
        toGrantsStatus: SUBMITTED
        toPath: /confirmation

      - fromGrantsStatus: SUBMITTED
        gasStatus: OFFER_SENT
        toGrantsStatus: SUBMITTED
        toPath: /confirmation

      - fromGrantsStatus: SUBMITTED
        gasStatus: OFFER_WITHDRAWN
        toGrantsStatus: SUBMITTED
        toPath: /confirmation

      - fromGrantsStatus: SUBMITTED
        gasStatus: OFFER_ACCEPTED
        toGrantsStatus: SUBMITTED
        toPath: /confirmation

      - fromGrantsStatus: SUBMITTED
        gasStatus: default
        toGrantsStatus: SUBMITTED
        toPath: /confirmation

      # Reopened
      - fromGrantsStatus: REOPENED
        gasStatus: default
        toGrantsStatus: REOPENED
        toPath: /summary

      # Cleared
      - fromGrantsStatus: CLEARED
        gasStatus: default
        toGrantsStatus: CLEARED
        toPath: /start

      # Awaiting amendments
      - fromGrantsStatus: AWAITING_AMENDMENTS
        gasStatus: default
        toGrantsStatus: REOPENED
        toPath: /summary

      # Default fallback
      - fromGrantsStatus: default
        gasStatus: default
        toGrantsStatus: SUBMITTED
        toPath: /confirmation
pages:
  - title: How will this project improve the environment?
    path: /environmental-impact
    section: environmentSection
    id: c6b1800f-b1f8-4874-a455-f1e007f1e0b5
  - title: 'Check your answers: Environment'
    path: /summary
    controller: SectionEndController
    id: 0d9d1728-b4cc-47b8-9527-dd7de25cc44b
lists: []
conditions: []
sections:
  - title: Environment
    name: environmentSection
    hideTitle: false
startPage: /environmental-impact
schema: 2
