# This is a basic workflow to help you get started with Actions

name: Test-Runners

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch.
  push:
    branches: [ "enable-runners" ]
  pull_request:
    branches: [ "enable-runners" ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name != 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run contract tests
        run: npm run test:contracts

      - name: Publish pacts
        env:
          PACT_BROKER_BASE_URL: https://ffc-pact-broker.azure.defra.cloud
          PACT_BROKER_USERNAME: ${{ secrets.PACT_USER }}
          PACT_BROKER_PASSWORD: ${{ secrets.PACT_PASS }}
        run: |
          ./node_modules/.bin/pact-broker \
            publish contracts/pacts \
            --auto-detect-version-properties
